services:
  postgres:
    restart: always
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: movim
      POSTGRES_USER: movim
      POSTGRES_PASSWORD: movim
  web:
    restart: always
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public-cache:/var/www/movim/public/cache:rw
    links:
      - fpm
      - daemon
  fpm:
    restart: always
    build:
      context: .
      target: fpm
      args:
        FPM_LISTEN: 0.0.0.0 # Listen everywhere for docker-compose.
    volumes:
      - ./movim.env:/var/www/movim/.env
      - ./cache:/var/www/movim/cache:rw
      - ./public-cache:/var/www/movim/public/cache:rw
      - ./log:/var/www/movim/log:rw
    links:
      - postgres
    depends_on:
      - postgres
  daemon:
    restart: always
    build:
      context: .
      target: daemon
    volumes:
      - ./movim.env:/var/www/movim/.env
      - ./cache:/var/www/movim/cache:rw
      - ./public-cache:/var/www/movim/public/cache:rw
      - ./log:/var/www/movim/log:rw
    links:
      - postgres
    depends_on:
      - postgres
